export default {
  appUrl: '$VITE_API_BASE_URL',
  keycloakUrl: '$VITE_AUTHENTICATION_KEYCLOAK_URL',
  keycloakRealm: '$VITE_AUTHENTICATION_KEYCLOAK_REALM',
  keycloakClientId: '$VITE_AUTHENTICATION_KEYCLOAK_CLIENT_ID',
  supersetUrl: '$VITE_SUPERSET_URL',
  piveauHubSearchUrl: '$VITE_API_HUB_SEARCH_URL',
  piveauHubRepoUrl: '$VITE_API_HUB_REPO_URL',
  piveauHubStoreUrl: '$VITE_API_HUB_STORE_URL',
  middlewareUrl: '$VITE_API_MIDDLEWARE_URL',
  piveauSparqlUrl: '$VITE_API_SPARQL_URL',
  piveauDataQualityUrl: '$VITE_API_DATA_QUALITY_URL',
  projectTitle: '$VITE_PROJECT_TITLE',
  projectUrl: '$VITE_PROJECT_URL',
  logoUrl: '$VITE_LOGO_URL',
  appTitle: '$VITE_APP_TITLE',
  themeColors: '$VITE_THEME_COLORS',
  socialLinkedIn: '$VITE_SOCIAL_LINKEDIN',
  socialTwitter: '$VITE_SOCIAL_TWITTER',
  socialYouTube: '$VITE_SOCIAL_YOUTUBE',
  socialFacebook: '$VITE_SOCIAL_FACEBOOK',
  socialGitHub: '$VITE_SOCIAL_GITHUB',
  contactEmail: '$VITE_CONTACT_EMAIL',
}
