export default {
  appUrl: 'http://localhost:5173',
  keycloakUrl: import.meta.env.VITE_AUTHENTICATION_KEYCLOAK_URL,
  keycloakRealm: import.meta.env.VITE_AUTHENTICATION_KEYCLOAK_REALM,
  keycloakClientId: import.meta.env.VITE_AUTHENTICATION_KEYCLOAK_CLIENT_ID,
  supersetUrl: '',
  piveauHubSearchUrl: import.meta.env.VITE_API_HUB_SEARCH_URL || 'https://demo.piveau.io/api/hub/search/',
  piveauHubRepoUrl: import.meta.env.VITE_API_HUB_REPO_URL || 'https://demo.piveau.io/api/hub/repo/',
  piveauHubStoreUrl: import.meta.env.VITE_API_HUB_STORE_URL || 'https://demo.piveau.io/api/hub/store/',
  piveauSparqlUrl: 'https://demo.piveau.io/sparql',
  piveauDataQualityUrl: import.meta.env.VITE_API_DATA_QUALITY_URL ?? 'https://demo.piveau.io/api/metrics/cache/',
  servicesCatalogue: import.meta.env.VITE_SERVICES_CATALOGUE || '6g-dali-services',
  projectTitle: import.meta.env.VITE_PROJECT_TITLE || '',
  projectUrl: import.meta.env.VITE_PROJECT_URL || '',
  logoUrl: import.meta.env.VITE_LOGO_URL || '/sparkworks-white.png',
  appTitle: import.meta.env.VITE_APP_TITLE || 'piveau - Metadata Catalogue',
  themeColors: import.meta.env.VITE_THEME_COLORS || '',
  socialLinkedIn: import.meta.env.VITE_SOCIAL_LINKEDIN || '',
  socialTwitter: import.meta.env.VITE_SOCIAL_TWITTER || '',
  socialYouTube: import.meta.env.VITE_SOCIAL_YOUTUBE || '',
  socialFacebook: import.meta.env.VITE_SOCIAL_FACEBOOK || '',
  socialGitHub: import.meta.env.VITE_SOCIAL_GITHUB || '',
  contactEmail: import.meta.env.VITE_CONTACT_EMAIL || '',
}
